# Form implementation generated from reading ui file 'Historial.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QTimer, pyqtSignal


class Ui_Historial(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 600)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Form)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 70, 531, 401))
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_2.setGeometry(QtCore.QRect(650, 50, 351, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(470, 540, 100, 32))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Historial"))
        self.groupBox_2.setTitle(_translate("Form", "Historial"))
        self.label_9.setText(_translate("Form", "Estado de la máquina:"))
        self.label_10.setText(_translate("Form", "Activo/Inactivo"))
        self.label_13.setText(_translate("Form", "Cantidad de producto:"))
        self.label_14.setText(_translate("Form", "20kilos"))
        self.label_11.setText(_translate("Form", "Anomalías:"))
        self.label_12.setText(_translate("Form", "# Fallas"))
        self.label_15.setText(_translate("Form", "Producido:"))
        self.label_16.setText(_translate("Form", "# Bolsas"))
        self.pushButton.setText(_translate("Form", "Regresar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)  # Crear la aplicación Qt
    Historial = QtWidgets.QDialog()  # Crear una instancia del QDialog
    ui = Ui_Historial()  # Crear la interfaz de usuario
    ui.setupUi(Historial)  # Configurar la interfaz en el dialog
    Historial.exec()  # Ejecutar el diálogo